---
# tasks file for apache-ubuntu role

- name: Instalar Apache Server
  apt:
    name: apache2
    state: latest
    update_cache: yes
    
- name: Start and enable apache service
  service:
    name: apache2
    state: started
    enabled: yes

- name: Configure firewall
  ufw:
    rule: allow
    src: '{{ item }}'
    state: enabled
  loop:
    - 80
    - 443      
